navikt/tiltak-refusjon-api

src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/tilskuddsperiode/TilskuddsperiodeKafkaLytter.kt, src/main/resources/application.yml
Oppdatert de resterende kafka-lytterne for tilskuddsperiode annullert og forkortet til å lese fra offset 0.
Usikker på om det trengs å byttes group-id. Samtidig så er jo de lytterne også over på den nye group-iden..
=> Lese fra offset 0 for annullert og forkortet topic

src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/Refusjon.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/RefusjonKafkaProducer.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/StatusJobb.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/events/RefusjonUtgått.kt, src/test/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/RefusjonTest.kt
Når statusjobben endrer status på en refusjon til `UTGÅTT` sendes det også melding på topic `tilskuddsperiode-annullert`, slik at midler frigjøres.
=> Frigjøre midler ved utgått refusjon

src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/RefusjonService.kt, src/test/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/TestData.kt, src/test/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/RefusjonServiceTest.kt
Gjort om til følgende regler:
henter 1 måned med inntekter som standard (den måneden som refusjonen gjelder for)
på sommerjobb hentes det likevel for måneden etter.
=> Hent 1 mnd inntekter

src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/Refusjon.kt, src/test/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/RefusjonTest.kt
Baserer maks forlengelse av frist på opprinnelig frist.
Opprinnelig frist har tidligere vært 2 måneder etter tilskuddTom. Det er endret, slik at om beslutter godkjenner tilskuddsperioden etter at tilskuddsperioden er ferdig, blir fristen satt 2 måneder etter godkjentAvBeslutterTidspunkt.
Dette må taes høyde for i reglene for forlengelse av frister, hvor man maks skal kunne forlenge 1 måned.
=> baserer maks forlengelse av frist på opprinnelig frist

src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/Refusjon.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/RefusjonKafkaProducer.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/RefusjonStatus.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/Refusjonsgrunnlag.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/events/RefusjonGodkjentMinusBeløp.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/events/RefusjonGodkjentNullBeløp.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/tilskuddsperiode/TilskuddsperiodeAnnullertMelding.kt, src/test/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/RefusjonServiceTest.kt, src/test/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/RefusjonTest.kt
Håndterer to caser:
- Godkjent "nullbeløp".
- Fikser annullering til oebs ved godkjent minus-beløp.
Noen tilfelder kan en refusjon gå i "null". Enten ved trekk for f eks sykefravær, eller triksing av tilskuddsbeløpet. Ordren i oebs må da annulleres.
=> Godkjent null belop

src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/Refusjonsgrunnlag.kt
Nuller ut og sletter en del data, som f eks beregning, når man velger nei til alle inntektslinjer. Dette gjør at frontend kan vise riktigte komponenter basert på riktig data.
=> Deleter beregning og andre valg om man velger nei på alle inntektslinjer

src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/Inntektslinje.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/Refusjon.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/Refusjonsgrunnlag.kt, src/test/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/IntegrasjonerMockServer.kt
inntektslinjer får ny ID hver gang inntekter hentes. Dette er problematisk, hvis man huker av for opptjent i perioden samtidig som inntektene hentes.
=> Unngå ny ID problem

src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/autorisering/InnloggetArbeidsgiver.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/autorisering/InnloggetBrukerService.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/autorisering/InnloggetSaksbehandler.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/dokgen/RefusjonTilPDFMapper.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/featuretoggles/FeatureToggleService.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/inntekt/FakeInntektskomponentService.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/pdf/RefusjonTilPDF.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/ArbeidsgiverRefusjonController.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/GodkjennEldreRefusjonFørstException.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/Minusbelop.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/MinusbelopRepository.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/Refusjon.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/RefusjonGodkjentLytter.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/RefusjonGodkjentMinusBeløpLytter.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/RefusjonService.kt, src/main/resources/db/migration/V35__flytter_minus_belop_egen_tabell.sql, src/test/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/IntegrasjonerMockServer.kt, src/test/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/TestData.kt, src/test/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/autorisering/InnloggetArbeidsgiverTest.kt, src/test/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/RefusjonApiTest.kt, src/test/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/RefusjonServiceTest.kt, src/test/resources/application-local.yml
Denne PR endrer hvordan sykepenger håndteres. Sykepenger legges inn på samme måte som tidligere, men man får nå mulighet å vente med å godkjenne til man faktisk har beløpet. Fristen utsettes automatisk 6 mnd om man velger JA.
Får å håndtere dette er rekkefølgekravet slettet. Det innebærer at evt minusbeløp grunne feriepenger ikke lenger lagres på en refusjon, men i egen tabelle knyttet til avtalenr. Man kan altså godkjenne refusjoner uten rekkefølgekrav og minusbeløp vil legges til den man godkjenner.
=> Sykepenger ikke rekkefolge

src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/inntekt/FakeInntektskomponentService.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/Inntektslinje.kt, src/test/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/inntekt/RefusjonsberegnerTest.kt, src/test/resources/application-local.yml, src/test/resources/features/refusjon.feature
Henter (eller snarere,  viser) inntektlinjer med type: "Uregelmessige tillegg knyttet til arbeidet tid"
Denne tas altså med i listen over inntekter som vises til arbeidsgiver.
=> Henter inntekter av ny type. Uregelmessige tillegg

src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/Inntektslinje.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/Refusjonsberegner.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/Refusjonsgrunnlag.kt, src/test/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/inntekt/RefusjonberegnerFratrekkFerieTest.kt, src/test/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/inntekt/RefusjonsberegnerTest.kt, src/test/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/RefusjonsberegningSteps.kt, src/test/resources/mappings/inntektskomponenten.json
Hvis man har valgt inntekter før flere måneder, f eks mai og juni, når man behandler mai-refusjonen så ble ferietrekk for juni trukket.
Det er nå fikset sånn at man bare trekker ferie når man faktisk er i refusjonen som har trekket.
=> Sjekker at man faktisk er i feripengemåneden før det beløpet trekkes

src/main/resources/db/migration/V45__index_pa_foreign_keys.sql
Har lagt til indeks på foreign keys fra refusjon->refusjonsgrunnlag->tilskuddsgrunnlag.
Dette bør hjelpe på sequence scans i de vanligste spørringene fra arbeidsgiver.
=> Lagt til indeks på foreign keys fra refusjon

src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/autorisering/InnloggetArbeidsgiver.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/ArbeidsgiverRefusjonController.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/Refusjon.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/RefusjonService.kt
Håndterer tilfelder hvor arbeidsgiver ikke har, eller ikke velger, inntekter for refusjonen. De kan da godkjenne den med null i beløp sånn at det ikke går ut på tid.
Midler blir frigitt.
=> Grunnleggende funksjonalitet for å kunne godkjenne nullrefusjon

src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/Refusjonsberegner.kt
Korreksjon av en refusjon som går i minus må regnes ut med riktig "tegn" på refusjonsbeløpet. Dette vil gi en totalsum som blir riktig.
Eksempel:
- Refusjonen med 18000 i inntekt og med ferietrekk har fått resultat -5553 kr.
- I korreksjonen velger man 20000 i inntekt, altså  2000 mer. Man forventer da at man får utbetalt litt ekstra (blir skydlig noe mindre)
- Utregningen i korreksjonen blir da (med korreksjonens metadata) 1587 kr
- Da dette blir en utbetalning vil man altså blir skydlig 1587 kr mindre totalt sett.
- Gjenværende minusbeløp på -5553 kr vil fortsatt trekkes en evt fremtidig refusjon. Men totalen blir altså riktig.
=> Korreksjon av en refusjon som gått i minus regnes nå ut riktig

src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/AdminController.kt
Dette er for å kunne liste ut og sjekke om det er mismatch i refusjonsløsning og økonomiløsning.
=> Admin-endepunkt: Hent refusjoner med status 'sendt krav'

src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/autorisering/InnloggetArbeidsgiver.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/autorisering/InnloggetSaksbehandler.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/RefusjonRepository.kt
Sortering på refusjonsoversikten for arbeidsgiver:
Sorterer på refusjon.id som secondary sort uansett hvilken primary sort man har, dermed vil alltid rekkefølgen bli lik selvom det er like verdier i primary sort.
TODO: fikse for veileder også.
=> Secondary sort på refusjonsid

src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/hendelseslogg/HendelsesloggRepository.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/SaksbehandlerRefusjonController.kt
Istedet for å hente alle hendelser og etterpå filtrere på refusjonsId i backend så gjør vi filtreringen i database istedet.
=> Hendelselogg henter alle hendelser på refusjonsId

src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/BetalingStatusKafkaLytter.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/Refusjon.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/RefusjonService.kt, src/test/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/RefusjonServiceTest.kt, src/test/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/RefusjonVarig5GTest.kt
På grunn av en feil i koden så kunne avtaler gå over 5G for et gitt år.
Vi oppretter en test som illustrerer problemet, men kort forklart: hvis en refusjon opprettes først året ETTER det året den egentlig gjelder for (feks desember-refusjon opprettes i januar), så ble ikke den totale summen for året kalkulert riktig. Algoritmen ville i stedet basere kalkulasjonen på andre refusjoner fra samme år som opprettet-tidspunktet (nyåret) i
stedet for perioden refusjonen gjaldt for (fjoråret).
I tillegg til denne bugfiksen har vi lagt til en test som også viser at refusjoner som gjelder for perioden etter grunnbeløp oppdateres vil gi en liten ekstra utbetaling (tilsvarende grunnbeløpsøkningen x 5)
=> Avtaler kunne overskride 5G for et år

src/test/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/CookieTokenFilter.kt, src/test/resources/application-dockercompose.yml, src/test/resources/application-local.yml
Siste oppgradering av token-validation-spring (v4) fjernet støtte for tokens som ligger i en cookie.
Det var vår måte å "logge inn" på i lokal utvikling.
Ved å redusere "presedensen" til valideringsfilteret og sette inn et "CookieTokenFilter" foran, kan vi
manuelt sette inn et token i auth-header som fanges opp av valideringsfilteret senere.
=> CookieTokenFilter for lokal utvikling

src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/autorisering/InnloggetBrukerService.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/autorisering/InnloggetSaksbehandler.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/autorisering/InternIdentifikatorer.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/autorisering/TilgangskontrollService.kt, src/test/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/autorisering/InnloggetSaksbehandlerTest.kt, src/test/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/RefusjonApiTest.kt
Opprett et abstraksjonslag for tilgang som også legger til rette for bruk av azure-id (som er brukt i poao-tilgang)
=> Rigge for migrering av abac til poao-tilgang

src/main/resources/db/migration/V55__indeks_refusjonsgrunnlag.sql
Analyse i prod viser at oppslag på refusjoner og
korreksjoner fører til en "seq scan" i beregning-
tabellen på 80000 rader ved hvert oppslag.
=> Index på refusjonsgrunnlag->beregning

src/main/resources/application-dev-gcp-labs.yml
Ved innlogging i labs kaster backenden feil grunnet
manglende verdi for dette feltet. Så vi kan løse det
ved å fylle inn en dummy-verdi.
=> Legg til beslutter ad-gruppe i labs

src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/hendelseslogg/Hendelseslogg.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/hendelseslogg/HendelsesloggDTO.kt, src/main/resources/application-dev-gcp-labs.yml, src/main/resources/db/migration/V58__tidssone_for_godkjent_av_arbeidsgiver.sql, src/main/resources/db/migration/V59__tidssone_for_utbetalt_tidspunkt.sql, src/main/resources/db/migration/V60__tidssone_for_hendelselogg_tidspunkt.sql, src/test/resources/application-dockercompose.yml
Databasekolonnen har ikke tidssone, men er mappet
til en instant i kodebasen (som har tidssone).
Denne migreringen setter tidssone på kolonnen slik at det ikke vil være forvirring (det er lett å tro at man ser på "norsk tid" i en spørring, når man
egentlig må legge på 2 timer for å se riktig tidspunkt)
=> Sett tidssone på godkjent_av_arbeidsgiver

src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/Korreksjon.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/Refusjon.kt, src/test/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/TestData.kt
For å unngå feilmelding når en VTAO-avtale godkjennes,
må vi gjøre en endring i backend som sjekker om man faktisk
må ta stilling til inntekter før man sjekker om det er blitt tatt
stilling til.
Foreløpig er det bare for VTAO-avtaler at man ikke må ta stilling
til inntekter, så sjekken er foreløpig ganske enkel.
Setter også opp litt VTAO-testdata
=> Fiks for VTAO og inntektslinjer

pom.xml
Denne endringen fjerner rundt 50-60 mb med
avhengigheter fra jar-pakken.
Jar-størrelse før endring: 145M
Jar-størrelse etter endring: 87M
Reduserer også antall sårbarheter:
=> Flytt avhengighet til test-scope

src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/ArbeidsgiverRefusjonController.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/SaksbehandlerRefusjonController.kt, src/test/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/RefusjonApiTest.kt
Dersom informasjonen til en deltaker dukker opp
i en listevisning, skal ikke dette medføre logging til arcsight.
Formålet med auditlogging er å logge oppslag på en spesifikk bruker, men listeoppslagene vil skape
unødvendig støy.
Dette er beskrevet i etterlevelseskrav K253.1
=> Ikke auditlogg listeoppslag

src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/Refusjon.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/RefusjonService.kt, src/test/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/RefusjonServiceTest.kt
Etterregistrerte vtao-avtaler skal automatisk utsendes. Men når vi mottar en slik refusjon burde vi ikke sende den til økonomiløsningen umiddelbart, da dette kan føre til at faktura blir forsøkt opprettet før ordre! Da vil fakturaen feile i økonomi.
Denne endringen vil føre til at etterregistrerte VTAO-refusjoner vil være merket "for tidlig" i én dag, før de sendes inn automatisk på natten.
=> Fiks "race condtion" for etterregistret VTAO

.github/workflows/bygg-og-deploy-labs.yml, .github/workflows/bygg-og-deploy.yml, .nais/wiremock.yml, DockerfileWiremock
En endring i Nais-plattformen gjorde at wiremock-imaget vårt ikke deployer lenger.
Denne endringen gjør at vi deployer wiremock på en litt mindre magisk måte, i tillegg til en fungerende måte.
=> Fiks labs - wiremock deployer ikke

src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/altinn/AltinnTilgangsstyringService.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/norg/NorgServiceImp.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/okonomi/KontoregisterServiceImpl.kt
Vi får en advarsel om at http-klienten produserer metrikker med for mange unike tags. Det betyr kort og godt at vi lager metrikker med metadata som feks:
`http_client_requests_active_seconds_sum{...,uri="/kontoregister/api/v1/hent-kontonummer-for-organisasjon/123456789"} 0.0`
i stedet for:
`http_client_requests_active_seconds_sum{...,uri="/kontoregister/api/v1/hent-kontonummer-for-organisasjon/{bedriftNr}"} 0.0`
Merk endringen på slutten av URL'en, hvor vi frem til nå har logget bedriftnummeret i stedet for en 'variabel'.
Løsningen på dette er å sende inn uri-variabler ("{bedriftNr}") i en egen hashmap. Vi slipper da også å potensielt logge fødselsnumre i prometheus-metrikkene våre.
=> Fiks warning om "maks uri-tags" i metrikker

src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/refusjon/Refusjonsberegner.kt, src/main/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/utils/5GSjekkerUtil.kt, src/test/kotlin/no/nav/arbeidsgiver/tiltakrefusjon/inntekt/RefusjonsberegnerTest.kt
I utregningen på en refusjon vil vi markere at beregnet beløp utgår dersom det er høyere enn tilskuddsbeløpet.
Problemet er at på tidspunktet vi sjekker om beløpet er over eller under tilskuddsbeløp så er beregnet beløp fortsatt en double! Senere så runder vi av til integer. Da kan vi ende opp med at beregnet beløp er 0.49 kroner over tilskuddsbeløp, men i utregningen ser det ut som begge beløp er identiske.
Vi løser dette ved å runde av til int FØR sjekkene på "over 5g" og "over tilskuddsbeløp".
=> Beregning påstår at beregnet beløp "utgår"
